/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.item;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author caiof
 */
public class ShowItensView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowItensView
     */
    public ShowItensView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spItens = new javax.swing.JScrollPane();
        lItens = new javax.swing.JList<>();
        lbTitulo = new javax.swing.JLabel();
        lbLegenda = new javax.swing.JLabel();

        setTitle("Itens");

        spItens.setViewportView(lItens);

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTitulo.setText("Itens Publicados");

        lbLegenda.setText("tipo Item | Sub-Categoria | Tamanho | Cor | Composicao | Preco Base |");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTitulo)
                    .addComponent(spItens, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addComponent(lbLegenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addComponent(lbLegenda)
                .addGap(1, 1, 1)
                .addComponent(spItens, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<JButton> lItens;
    private javax.swing.JLabel lbLegenda;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JScrollPane spItens;
    // End of variables declaration//GEN-END:variables

    public JList<JButton> getLItens(){
        return lItens;
    }
    
    public JLabel getLbTitulo(){
        return lbTitulo;
    }
    
    public JScrollPane getSpItens(){
        return spItens;
    }
     
}
