/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.item;

import javax.swing.*;

/**
 *
 * @author caiof
 */
public class ShowItemView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowItemView
     */
    public ShowItemView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtIdCItem = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        txtTipoItem = new javax.swing.JLabel();
        lblSubcategoria = new javax.swing.JLabel();
        txtSubcategoriaItem = new javax.swing.JLabel();
        lblTamanho = new javax.swing.JLabel();
        txtTamanhoItem = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        txtPesoItem = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        txtCorItem = new javax.swing.JLabel();
        lblComposicao = new javax.swing.JLabel();
        txtComposicaoItem = new javax.swing.JLabel();
        lblPrecoBase = new javax.swing.JLabel();
        txtPrecoBaseItem = new javax.swing.JLabel();
        lblDefeitos = new javax.swing.JLabel();
        spDefeitos = new javax.swing.JScrollPane();
        lTiposDefeito = new javax.swing.JList<>();
        lblVendedor = new javax.swing.JLabel();
        txtVendedorDados = new javax.swing.JLabel();
        lblOfertas = new javax.swing.JLabel();
        lblLegendaOferta = new javax.swing.JLabel();
        spOfertas = new javax.swing.JScrollPane();
        lOfertas = new javax.swing.JList<>();
        btnCancelar = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Item : ");

        txtIdCItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTipo.setText("Tipo:");

        txtTipoItem.setText("{tipo}");

        lblSubcategoria.setText("Sub-Categoria:");

        txtSubcategoriaItem.setText("{Subcategoria}");

        lblTamanho.setText("Tamanho:");

        txtTamanhoItem.setText("{Tamanho}");

        lblPeso.setText("Peso:");

        txtPesoItem.setText("{Peso}");

        lblCor.setText("Cor:");

        txtCorItem.setText("{Cor}");

        lblComposicao.setText("Composição:");

        txtComposicaoItem.setText("{Composicao}");

        lblPrecoBase.setText("Preço base:");

        txtPrecoBaseItem.setText("{Preco base}");

        lblDefeitos.setText("Defeitos:");

        spDefeitos.setViewportView(lTiposDefeito);

        lblVendedor.setText("Vendedor:");

        txtVendedorDados.setText("{vendedorid} + ({nivel})");

        lblOfertas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblOfertas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOfertas.setText("Ofertas");

        lblLegendaOferta.setText("Comprador | Preço Ofertado | data Oferta | status");

        spOfertas.setViewportView(lOfertas);

        btnCancelar.setText("Sair");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDefeitos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecoBaseItem, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComposicaoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spDefeitos, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTamanho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSubcategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPeso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPesoItem, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtTamanhoItem, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtSubcategoriaItem, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtTipoItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCorItem, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtIdCItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtVendedorDados, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblOfertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spOfertas)
                            .addComponent(lblLegendaOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdCItem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVendedorDados, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubcategoriaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOfertas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTamanhoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLegendaOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtComposicaoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecoBaseItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDefeitos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spDefeitos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(spOfertas))
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JList<JPanel> lOfertas;
    private javax.swing.JList<String> lTiposDefeito;
    private javax.swing.JLabel lblComposicao;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblDefeitos;
    private javax.swing.JLabel lblLegendaOferta;
    private javax.swing.JLabel lblOfertas;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPrecoBase;
    private javax.swing.JLabel lblSubcategoria;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JScrollPane spDefeitos;
    private javax.swing.JScrollPane spOfertas;
    private javax.swing.JLabel txtComposicaoItem;
    private javax.swing.JLabel txtCorItem;
    private javax.swing.JLabel txtIdCItem;
    private javax.swing.JLabel txtPesoItem;
    private javax.swing.JLabel txtPrecoBaseItem;
    private javax.swing.JLabel txtSubcategoriaItem;
    private javax.swing.JLabel txtTamanhoItem;
    private javax.swing.JLabel txtTipoItem;
    private javax.swing.JLabel txtVendedorDados;
    // End of variables declaration//GEN-END:variables


    public JLabel getTxtIdCItem() {
        return txtIdCItem;
    }

    public JLabel getTxtTipoItem() {
        return txtTipoItem;
    }

    public JLabel getTxtSubcategoriaItem() {
        return txtSubcategoriaItem;
    }

    public JLabel getTxtTamanhoItem() {
        return txtTamanhoItem;
    }

    public JLabel getTxtPesoItem() {
        return txtPesoItem;
    }

    public JLabel getTxtCorItem() {
        return txtCorItem;
    }

    public JLabel getTxtComposicaoItem() {
        return txtComposicaoItem;
    }

    public JLabel getTxtPrecoBaseItem() {
        return txtPrecoBaseItem;
    }

    public JScrollPane getSpDefeitos() {
        return spDefeitos;
    }

    public JList<String> getlTiposDefeito() {
        return lTiposDefeito;
    }

    public JLabel getTxtVendedorDados() {
        return txtVendedorDados;
    }

    public JScrollPane getSpOfertas() {
        return spOfertas;
    }

    public JList<JPanel> getlOfertas() {
        return lOfertas;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }
}
