/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author berna
 */
public class HomeView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeView.class.getName());

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }
    
        
    public JButton getBtnComprador() {
        return btnAcessarPerfilComprador;
    }
    
    public JButton getBtnVendedor() {
        return btnAcessarPerfilVendedor;
    }    
    
    public JButton getBtnCriarPerfilComprador() {
        return btnCriarPerfilComprador;
    }
    
    public JButton getBtnCriarPerfilVendedor() {
        return btnCriarPerfilVendedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCriarPerfilComprador = new javax.swing.JButton();
        btnCriarPerfilVendedor = new javax.swing.JButton();
        btnAcessarPerfilComprador = new javax.swing.JButton();
        btnAcessarPerfilVendedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        btnCriarPerfilComprador.setText("Criar Perfil Comprador");

        btnCriarPerfilVendedor.setText("Criar Perfil Vendedor");
        btnCriarPerfilVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarPerfilVendedorActionPerformed(evt);
            }
        });

        btnAcessarPerfilComprador.setText("Acessar Perfil Comprador");

        btnAcessarPerfilVendedor.setText("Acessar Perfil Vendedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCriarPerfilComprador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAcessarPerfilComprador, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCriarPerfilVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAcessarPerfilVendedor))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarPerfilComprador)
                    .addComponent(btnCriarPerfilVendedor))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcessarPerfilComprador)
                    .addComponent(btnAcessarPerfilVendedor))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarPerfilVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarPerfilVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarPerfilVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessarPerfilComprador;
    private javax.swing.JButton btnAcessarPerfilVendedor;
    private javax.swing.JButton btnCriarPerfilComprador;
    private javax.swing.JButton btnCriarPerfilVendedor;
    // End of variables declaration//GEN-END:variables
}
