/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author berna
 */
public class HomeView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeView.class.getName());

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        jDesktopPane = new JDesktopPane();
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setContentPane(jDesktopPane);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        menuItemEntrar = new javax.swing.JMenuItem();
        menuItemCadastrar = new javax.swing.JMenuItem();
        menuItemSair = new javax.swing.JMenuItem();
        menuVendedor = new javax.swing.JMenu();
        mItemCriarPerfilVendedor = new javax.swing.JMenuItem();
        mItemAcessarPerfilVendedor = new javax.swing.JMenuItem();
        menuComprador = new javax.swing.JMenu();
        mItemCriarPerfilComprador = new javax.swing.JMenuItem();
        mItemAcessarPerfilComprador = new javax.swing.JMenuItem();
        menuItem = new javax.swing.JMenu();
        mItemPublicarItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        menuUsuario.setText("Usuario");

        menuItemEntrar.setText("Entrar");
        menuItemEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEntrarActionPerformed(evt);
            }
        });
        menuUsuario.add(menuItemEntrar);

        menuItemCadastrar.setText("Cadastrar");
        menuUsuario.add(menuItemCadastrar);

        menuItemSair.setText("Sair");
        menuUsuario.add(menuItemSair);

        jMenuBar1.add(menuUsuario);

        menuVendedor.setText("Vendedor");

        mItemCriarPerfilVendedor.setText("Criar Perfil");
        menuVendedor.add(mItemCriarPerfilVendedor);

        mItemAcessarPerfilVendedor.setText("Acessar");
        menuVendedor.add(mItemAcessarPerfilVendedor);

        jMenuBar1.add(menuVendedor);

        menuComprador.setText("Comprador");

        mItemCriarPerfilComprador.setText("Criar Perfil");
        menuComprador.add(mItemCriarPerfilComprador);

        mItemAcessarPerfilComprador.setText("Acessar");
        mItemAcessarPerfilComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAcessarPerfilCompradorActionPerformed(evt);
            }
        });
        menuComprador.add(mItemAcessarPerfilComprador);

        jMenuBar1.add(menuComprador);

        menuItem.setText("Item");

        mItemPublicarItem.setText("Publicar Item");
        menuItem.add(mItemPublicarItem);

        jMenuBar1.add(menuItem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemAcessarPerfilCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAcessarPerfilCompradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mItemAcessarPerfilCompradorActionPerformed

    private void menuItemEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItemAcessarPerfilComprador;
    private javax.swing.JMenuItem mItemAcessarPerfilVendedor;
    private javax.swing.JMenuItem mItemCriarPerfilComprador;
    private javax.swing.JMenuItem mItemCriarPerfilVendedor;
    private javax.swing.JMenuItem mItemPublicarItem;
    private javax.swing.JMenu menuComprador;
    private javax.swing.JMenu menuItem;
    private javax.swing.JMenuItem menuItemCadastrar;
    private javax.swing.JMenuItem menuItemEntrar;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menuVendedor;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getDesktopPane() {
        return jDesktopPane;
    }
    
    public JMenu getMenuUsuario(){
        return menuUsuario;
    }
    
        public JMenuItem getMItemEntrarUsuario(){
            return menuItemEntrar;
        }

        public JMenuItem getMItemCadastrarUsuario(){
            return menuItemCadastrar;
        }

        public JMenuItem getMItemSairUsuario(){
            return menuItemSair;
        }
    
        
    public JMenu getMenuVendedor(){
        return menuVendedor;
    }
    
        public JMenuItem getMItemCriarPerfilVendedor() {
            return mItemCriarPerfilVendedor;
        }

        public JMenuItem getMItemAcessarPerfilVendedor() {
            return mItemAcessarPerfilVendedor;
        }
    
        
    public JMenu getMenuComprador(){
        return menuComprador;
    }
     
        public JMenuItem getMItemCriarPerfilComprador() {
            return mItemCriarPerfilComprador;
        }

        public JMenuItem getMItemAcessarPerfilComprador() {
            return mItemAcessarPerfilComprador;
        }
    
    public JMenu getMenuItem(){
        return menuItem;
    }
    
        public JMenuItem getMItemPublicarItem(){
            return mItemPublicarItem;
        }
}
