/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

/**
 *
 * @author caiof
 */
public class PerfilView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PerfilVendedorView
     */
    public PerfilView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        lbNome = new javax.swing.JLabel();
        lbBeneficio = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtBeneficio = new javax.swing.JLabel();
        lbInsignia = new javax.swing.JLabel();
        spInsignias = new javax.swing.JScrollPane();
        lbMedalha = new javax.swing.JLabel();
        spMedalhas = new javax.swing.JScrollPane();
        btnFunc1 = new javax.swing.JButton();
        lbNivel = new javax.swing.JLabel();
        txtNivel = new javax.swing.JLabel();
        txtEstrelas = new javax.swing.JLabel();
        lbEstrela = new javax.swing.JLabel();
        btnFunc3 = new javax.swing.JButton();
        btnFunc2 = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();

        jButton3.setText("Ver Ofertas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setTitle("Meu Perfil");

        lbNome.setText("Nome:");

        lbBeneficio.setText("Beneficio Climatico:");

        txtNome.setText("{nome}");

        txtBeneficio.setText("{Beneficio}");

        lbInsignia.setText("Insignias:");

        lbMedalha.setText("Medalhas:");

        btnFunc1.setText("btn1");
        btnFunc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunc1ActionPerformed(evt);
            }
        });

        lbNivel.setText("Nivel:");

        txtNivel.setText("{nivel}");

        txtEstrelas.setText("{Estrelas}");

        lbEstrela.setText("Estrelas:");

        btnFunc3.setText("btn3");
        btnFunc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunc3ActionPerformed(evt);
            }
        });

        btnFunc2.setText("btn2");
        btnFunc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunc2ActionPerformed(evt);
            }
        });

        btnHistorico.setText("Historico");
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addComponent(btnFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFunc3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbBeneficio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbInsignia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMedalha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNivel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNivel)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(lbEstrela, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstrelas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spInsignias)
                            .addComponent(spMedalhas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBeneficio)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHistorico)))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNome)
                            .addComponent(txtNome)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHistorico)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNivel)
                    .addComponent(txtNivel)
                    .addComponent(lbEstrela)
                    .addComponent(txtEstrelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBeneficio)
                    .addComponent(txtBeneficio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbInsignia)
                    .addComponent(spInsignias, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMedalha)
                    .addComponent(spMedalhas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFunc1)
                    .addComponent(btnFunc3)
                    .addComponent(btnFunc2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFunc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFunc1ActionPerformed

    private void btnFunc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFunc3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnFunc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFunc2ActionPerformed

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoricoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFunc1;
    private javax.swing.JButton btnFunc2;
    private javax.swing.JButton btnFunc3;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lbBeneficio;
    private javax.swing.JLabel lbEstrela;
    private javax.swing.JLabel lbInsignia;
    private javax.swing.JLabel lbMedalha;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JLabel lbNome;
    private javax.swing.JScrollPane spInsignias;
    private javax.swing.JScrollPane spMedalhas;
    private javax.swing.JLabel txtBeneficio;
    private javax.swing.JLabel txtEstrelas;
    private javax.swing.JLabel txtNivel;
    private javax.swing.JLabel txtNome;
    // End of variables declaration//GEN-END:variables
    
    public JLabel getTxtNome() {
        return txtNome;
    }

    public JLabel getTxtBeneficio() {
        return txtBeneficio;
    }

    public JLabel getTxtNivel() {
        return txtNivel;
    }

    public JLabel getTxtEstrelas() {
        return txtEstrelas;
    }

    public JButton getBtnFunc1() {
        return btnFunc1;
    }

    public JButton getBtnFunc2() {
        return btnFunc2;
    }

    public JButton getBtnFunc3() {
        return btnFunc3;
    }

    public JButton getBtnHistorico() {
        return btnHistorico;
    }

    public JScrollPane getSpInsignias() {
        return spInsignias;
    }

    public JScrollPane getSpMedalhas() {
        return spMedalhas;
    }
}
